"""Create all tables

Revision ID: 70389c0560b1
Revises: e0f5321551c2
Create Date: 2025-07-25 21:21:24.813035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70389c0560b1'
down_revision = 'e0f5321551c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_session_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(op.f('fk_bios_speaker_id_speakers'), 'bios', 'speakers', ['speaker_id'], ['id'])
    op.create_foreign_key(op.f('fk_sessions_event_id_events'), 'sessions', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sessions_event_id_events'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_bios_speaker_id_speakers'), 'bios', type_='foreignkey')
    op.drop_table('session_speakers')
    # ### end Alembic commands ###
